output_dir: ~/scratch/torchprotein_output/

dataset:
  class: BinaryLocalization
  path: ~/scratch/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: "residue"

task:
  class: PropertyPrediction
  model:
    class: ProteinLSTM
    input_dim: 21
    hidden_dim: 640
    num_layers: 3
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2
  num_class: 2
  batchnorm: True
  aug: APA
  ig: True

eval_metric: accuracy

optimizer:
  class: Adam
  lr: 5.0e-5

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 32

train:
  num_epoch: 75

protein_auto_augment:
  search: True
  finetune_num: 25
  finetune_epoch: 5
  num_subpolicy: 4
  num_op: 2


