output_dir: ~/scratch/torchprotein_output/

dataset:
  class: EnzymeCommission
  path: ~/scratch/protein-datasets/
  test_cutoff: 0.95
  atom_feature: null
  bond_feature: null
  transform:
    class: ProteinView
    view: residue

task:
  class: MultipleBinaryClassification
  model:
    class: ProteinLSTM
    input_dim: 21
    hidden_dim: 640
    num_layers: 3
  criterion: bce
  metric: ['auprc@micro', 'f1_max']
  num_mlp_layer: 3
  batchnorm: True
  aug: APA
  ig: True
  
eval_metric: auprc@micro

optimizer:
  class: Adam
  lr: 5.0e-5

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 8

train:
  num_epoch: 95

protein_auto_augment:
  search: True
  finetune_num: 10
  finetune_epoch: 5
  num_subpolicy: 4
  num_op: 2