output_dir: ~/scratch/torchprotein_output/

dataset:
  class: SubcellularLocalization
  path: ~/scratch/protein-datasets/
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: TruncateProtein
        max_length: 550
        random: True
      - class: ProteinView
        view: "residue"

task:
  class: PropertyPrediction
  model:
    class: ESM
    path: ~/scratch/protein-model-weights/esm-model-weights/
    model: ESM-2-35M
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2
  batchnorm: True
  aug: APA
  ig: True
  
eval_metric: accuracy

optimizer:
  class: Adam
  lr: 2.0e-4

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 4

lr_ratio: 0.1

train:
  num_epoch: 25

protein_auto_augment:
  search: True
  finetune_num: 25
  finetune_epoch: 5
  num_subpolicy: 4
  num_op: 2
